name: nerf2mesh
dependencies:
- python>=3.5
# - anaconda
- pip
- pip:
  - torch
  - git+https://github.com/NVlabs/nvdiffrast/
  - rich
  - tqdm
  - ninja
  - torch
  - numpy
  - scipy
  - lpips
  - pandas
  - trimesh
  - PyMCubes
  - torch-ema
  - dearpygui
  - packaging
  - matplotlib
  - tensorboardX
  - opencv-python
  - imageio
  - imageio-ffmpeg
  - pymeshlab
  # - torch-scatter
  - xatlas
  - scikit-learn
  - torchmetrics
